#+Title:  Internal Reviews of IIITH Integration Process 
#+Author: Soujanya
#+Date:   <2015-02-11 Wed>

* Attendees
 - Geeta, Soujanya
* Agenda
** Immediate Action Items
*** Get a public IP for cloning Client Side Dependencies (on Amazon/IIIT-H server) 
 As part of our Integration process, labs having client side
 dependencies will be provided with a link to download softwares as
 per requirement along with the installation/configuration
 process. Raise a ticket on github engineers-forum.
*** Find out a way to get labs running on "Multiple Containers" tested over ADS. Currently there are 4 labs among 20, which are:
    - Databases [Level 4]
    - Data Mining [Level 4]
    - Linux Lab[Level 4]
    - Principles of Programming Languages [Level 1]
*** Test the labs from an end user's perspective
 Check for proper functionality of links, images and simulations along with user interation. Based on the analysis come up with improvements/suggestions to enhance the quality of lab   
*** Two machines needed for interns to work on
*** Windows license for testing labs
** Task allocation among the team 
